insert into chow_hound_db.cuisines (id, description, is_primary, category) values (1, 'Mexican', 1, 'Mexican');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (2, 'Italian', 1, 'Italian');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (3, 'Pizza', 1, 'Pizza');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (4, 'Tacos', 1, 'Tacos');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (5, 'Puerto Rican', 0, 'Puerto Rican');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (6, 'Sandwiches', 1, 'Sandwiches');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (7, 'American', 1, 'American');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (8, 'Asian', 1, 'Asian');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (9, 'Seafood', 1, 'Seafood');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (10, 'Chinese', 0, 'Chinese');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (11, 'Thai', 0, 'Thai');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (12, 'Sushi', 0, 'Sushi');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (13, 'Hamburgers', 1, 'Hamburgers');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (14, 'Breakfast', 1, 'Breakfast');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (15, 'BBQ', 1, 'BBQ');
insert into chow_hound_db.cuisines (id, description, is_primary, category) values (16, 'Mediterranean', 1, 'Mediterranean');
